### ISSUE TITLE
Inconsistencies in naming stuff

### ISSUE THREAD

**Issue by rmjordas** [projectunic0rn/mentorship-ui#111]
Some files are named with camelCase and other using PascalCase. Airbnb react style guide recommends the latter for filenames \[0] but we can use any.

Also, consider updating PascalCased keys in object definitions and interfaces <ins>to be camelCased.</ins>

**EDIT**:
- clarification on object and interface keys

\[0]: https://github.com/airbnb/javascript/tree/master/react#naming

**Comment by roymoran** [comment]
@ruj I agree. We can rename files. 

There might be a challenge with having all interface keys as PascalCased since some places in our code we do this - 

`this.api.getMentorMentorships(id).then((response: IMentorship[]) => {
      if (!this.cachedMentorshipsSame(cachedMentorMentorships, response)) {
        SessionService.StoreMentorMentorships(response);
        const pendingMentorshipRequest = this.filterPendingMentorships(response);
        this.setState({
          requests: pendingMentorshipRequest
        });
      }
});`

And the api response keys are in camelCase. Is there a work around here? or maybe we shouldn't specify the response type. What do you think?

**Comment by rmjordas** [comment]
No, sorry. I was thinking of updating all PascalCased object keys and interfaces to be camelCased.

**Comment by roymoran** [comment]
okay that works. I created a branch so that I can make the changes to the interfaces once we merge in the currently active PR's. https://github.com/projectunic0rn/mentorship-ui/tree/interface-camelcase
