### ISSUE TITLE
Mentor mentorships tab error

### ISSUE THREAD

**Issue by rickywid** [projectunic0rn/mentorship-ui#134]
when a user visits a mentor's profile page and tries to view the mentorships tab, the user will receive an error message. 

"TypeError: mentorship.user is undefined"

Screenshot
https://i.imgur.com/kBnKExA.png

**Comment by rmjordas** [comment]
When shared `ProfileMentorships` component tries to access its prop values, the value of `mentorship.user` (inside the `this.props.mentorships.map` function callback) is `undefined`. This is because the mocked API response of `getMentorProfile` has a `User` key instead of `user`.

https://github.com/projectunic0rn/mentorship-ui/blob/6fad03ddc5df281fe9df5da720cc5ce3babc0e07/src/components/shared/profileMentorships.tsx#L28-L35

https://github.com/projectunic0rn/mentorship-ui/blob/6fad03ddc5df281fe9df5da720cc5ce3babc0e07/src/mockServices/mockApiServiceResponses/getMentorProfile.ts#L18-L27

**Comment by roymoran** [comment]
Duplicate issue #174. closing this one.
